services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hono_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/backend/node_modules
    depends_on:
      - db
    working_dir: /workspace/backend

  frontend:
    image: node:20-alpine
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    working_dir: /workspace/frontend
    command: sh -c "npm install -g pnpm && tail -f /dev/null"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000

volumes:
  postgres_data:
  node_modules:
  frontend_node_modules: