name: Backend Deploy Debug

on:
  workflow_dispatch:
  push:
    branches:
      - staging

env:
  AWS_REGION: ap-northeast-1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  ENVIRONMENT: stg

permissions:
  id-token: write
  contents: read

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-github-actions
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push test
        run: |
          ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY="${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"
          IMAGE_TAG="${{ github.sha }}"
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          
          echo "ECR_REGISTRY: ${ECR_REGISTRY}"
          echo "ECR_REPOSITORY: ${ECR_REPOSITORY}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          echo "IMAGE_URI: ${IMAGE_URI}"
          
          # backendディレクトリの確認
          if [ -d "backend" ]; then
            echo "backend directory exists"
            ls -la backend/
          else
            echo "ERROR: backend directory not found!"
            exit 1
          fi
          
          # Dockerfileの確認
          if [ -f "backend/Dockerfile" ]; then
            echo "Dockerfile exists"
          else
            echo "ERROR: backend/Dockerfile not found!"
            exit 1
          fi
          
          # ビルドとプッシュ
          cd backend
          docker build -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}
          
          echo "Successfully pushed: ${IMAGE_URI}"